services:
    cli:
        image: node:alpine
        profiles:
            - cli
        volumes:
            - ./:/var/www/
        working_dir: /var/www/

    dev:
        image: node:alpine
        volumes:
            - ./:/var/www/
        working_dir: /var/www/

    prod:
        image: node:alpine
        profiles:
            - prod
        volumes:
            - ./:/var/www/
        working_dir: /var/www/
